name: authenticator
description: Securely use multi factor authentication for your favorite websites ands apps
version: 1.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  local_auth: ^0.3.1
  shared_preferences: ^0.4.3
  otp: 1.0.1
  sqflite: 0.13.0+1
  path_provider: 0.4.1
  flutter_slidable: ^0.4.9
  qr_mobile_vision: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true